# Generated by Django 5.2.5 on 2025-09-04 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested', to='JOB.job')),
            ],
        ),
    ]
