# Generated by Django 5.2.5 on 2025-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0002_interestedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_logo', models.URLField()),
                ('com_name', models.TextField(max_length=30)),
                ('com_calture', models.TextField(max_length=200)),
                ('com_hq', models.TextField(max_length=20)),
                ('com_ratings', models.IntegerField()),
                ('com_website', models.URLField()),
            ],
        ),
    ]
