# Generated by Django 5.2.5 on 2025-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOB', '0003_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='com_calture',
        ),
        migrations.AddField(
            model_name='companies',
            name='com_culture',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companies',
            name='com_hq',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companies',
            name='com_name',
            field=models.TextField(),
        ),
    ]
